United Users and Organisations into a single file
Due to cyclical reference the software only works correctly if the two were together

Error: Comparing __main__.Partner with Organisation.Partner